name: 'release direwolf packages'

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: 'Windows Latest MinGW 64bit',
              os: windows-latest,
              cc: 'x86_64-w64-mingw32-gcc',
              cxx: 'x86_64-w64-mingw32-g++',
              ar: 'x86_64-w64-mingw32-ar',
              windres: 'x86_64-w64-mingw32-windres',
              arch: 'x86_64',
              build_type: 'Release',
              cmake_extra_flags: '-G "MinGW Makefiles"'
            }
          - {
              name: 'macOS latest',
              os: macos-latest,
              cc: 'clang',
              cxx: 'clang++',
              arch: 'x86_64',
              build_type: 'Release',
              cmake_extra_flags: ''
            }
          - {
              name: 'Ubuntu 22.04',
              os: ubuntu-22.04,
              cc: 'gcc',
              cxx: 'g++',
              arch: 'x86_64',
              build_type: 'Release',
              cmake_extra_flags: ''
            }

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 8

      - name: dependency
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libasound2-dev libudev-dev libhamlib-dev gpsd
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install portaudio hamlib gpsd hidapi
          elif [ "$RUNNER_OS" == "Windows" ]; then
            echo "C:\msys64\mingw32\bin" >> $GITHUB_PATH
          fi

      - name: create build environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: configure
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            export CC=${{ matrix.config.cc }}
            export CXX=${{ matrix.config.cxx }}
            export AR=${{ matrix.config.ar }}
            export WINDRES=${{ matrix.config.windres }}
          fi
          cmake $GITHUB_WORKSPACE \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
            ${{ matrix.config.cmake_extra_flags }}

      - name: build
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            export CC=${{ matrix.config.cc }}
            export CXX=${{ matrix.config.cxx }}
            export AR=${{ matrix.config.ar }}
            export WINDRES=${{ matrix.config.windres }}
          fi
          cmake --build . --config ${{ matrix.config.build_type }}

      - name: package
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: make package

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: direwolf_${{ matrix.config.os }}_${{ matrix.config.arch }}
          path: ${{github.workspace}}/build/direwolf-*.zip

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: Release

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: Release/**/*.zip
          generate_release_notes: true
